# Generated by Django 4.2.3 on 2023-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BIC_SWIFT',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='CVV',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Favourite_city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='Favourite_national_team',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='IBAN_accountNumber',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='account_name',
            field=models.CharField(max_length=53, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address_gmail',
            field=models.CharField(max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='club_coeur',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_date',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_language',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mobile_phone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_gmail',
            field=models.CharField(max_length=95, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_user',
            field=models.CharField(max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe_user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='street_address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
